# Generated by Django 4.2.17 on 2025-01-15 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_query_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_query_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
