# Generated by Django 4.2.17 on 2025-01-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_daily_query_count_user_last_query_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
