# Generated by Django 4.2.18 on 2025-02-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_query_results_query_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bias_rating',
            field=models.CharField(choices=[('L', 'Left'), ('LL', 'Lean Left'), ('C', 'Center'), ('LR', 'Lean Right'), ('R', 'Right')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
