# Generated by Django 4.2.17 on 2025-02-05 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_user_allstars_argumentrating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="argumentrating",
            unique_together={("user", "core_argument")},
        ),
    ]
