# Generated by Django 4.2.17 on 2025-02-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_argumentrating_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="argumentrating",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="user",
            name="bias_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "Left"),
                    ("CL", "Center Left"),
                    ("C", "Center"),
                    ("CR", "Center Right"),
                    ("R", "Right"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_query_reset",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="argumentrating",
            constraint=models.UniqueConstraint(
                fields=("user", "core_argument"), name="unique_user_argument_rating"
            ),
        ),
    ]
