# Generated by Django 4.2.17 on 2025-02-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_argumentrating_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="daily_query_limit",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_user",
        ),
    ]
