# Generated by Django 4.2.17 on 2025-02-07 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_user_options_user_daily_query_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("cache_hits", models.IntegerField(default=0)),
                ("cache_misses", models.IntegerField(default=0)),
                ("memory_usage", models.FloatField(default=0.0)),
                ("total_entries", models.IntegerField(default=0)),
                ("hit_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "Cache Statistics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="last_query_reset",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
