# Generated by Django 4.2.17 on 2025-02-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_cachestatistics_alter_user_last_query_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="system_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
