# Generated by Django 4.2.17 on 2025-02-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_query_system_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="argumentrating",
            name="argument_source",
            field=models.CharField(default="gpt-4", max_length=50),
        ),
    ]
