# Generated by Django 4.2.17 on 2025-02-07 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_argumentrating_argument_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="argumentrating",
            name="argument_source",
            field=models.CharField(default="gpt-4", max_length=500),
        ),
        migrations.AlterField(
            model_name="user",
            name="daily_query_limit",
            field=models.IntegerField(default=20),
        ),
    ]
