# Generated by Django 4.2.17 on 2025-02-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_user_reset_time_alter_argumentrating_argument_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bias_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "Left"),
                    ("LL", "Lean Left"),
                    ("C", "Center"),
                    ("LR", "Lean Right"),
                    ("R", "Right"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
