# Generated by Django 4.2.17 on 2025-02-21 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_thumbsrating"),
        ("api", "0014_alter_user_bias_rating"),
    ]

    operations = []
