# Generated by Django 4.2.17 on 2025-02-21 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_add_stance_to_thumbsrating"),
        ("api", "0015_merge_0009_thumbsrating_0014_alter_user_bias_rating"),
    ]

    operations = []
