# Generated by Django 4.2.18 on 2025-02-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_update_user_query_reset'),
        ('api', '0016_merge_20250221_0710'),
    ]

    operations = [
    ]
