# Generated by Django 4.2.17 on 2025-03-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_researchreport_researchsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchreport",
            name="thread_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
