# Generated by Django 4.2.17 on 2025-03-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_researchreport_thread_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchreport",
            name="last_event",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="researchreport",
            name="last_event_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="researchreport",
            index=models.Index(
                fields=["thread_id"], name="api_researc_thread__2a09f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchreport",
            index=models.Index(fields=["status"], name="api_researc_status_61d7c2_idx"),
        ),
        migrations.AddIndex(
            model_name="researchreport",
            index=models.Index(
                fields=["user", "status"], name="api_researc_user_id_8bb10d_idx"
            ),
        ),
    ]
